resources:
- name: test-cfmgmt
  type: git
  source:
    uri: {{git_repo_uri}}
    branch: master
- name: 15m
  type: time
  source: {interval: 15m}

jobs:
- name: create-orgs
  plan:
  - get: test-cfmgmt
    trigger: true
  - task: create-orgs
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: create-orgs
- name: delete-orgs
  plan:
  - get: test-cfmgmt
    trigger: true
  - get: 15m
    trigger: true
  - task: delete-orgs
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: delete-orgs
- name: create-org-private-domains
  plan:
  - get: test-cfmgmt
    passed: [create-orgs]
    trigger: true
  - task: create-org-private-domains
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      LDAP_PASSWORD: {{ldap_password}}
      CF_MGMT_COMMAND: create-org-private-domains
- name: create-spaces
  plan:
  - get: test-cfmgmt
    passed: [create-orgs]
    trigger: true
  - task: create-spaces
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      LDAP_PASSWORD: {{ldap_password}}
      CF_MGMT_COMMAND: create-spaces
- name: delete-spaces
  plan:
  - get: test-cfmgmt
    passed: [create-orgs]
    trigger: true
  - get: 15m
    trigger: true
  - task: delete-spaces
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: delete-spaces
- name: update-spaces
  plan:
  - get: test-cfmgmt
    passed: [create-spaces]
    trigger: true
  - task: update-spaces
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: update-spaces
- name: update-space-users
  plan:
  - get: test-cfmgmt
    passed: [create-spaces]
    trigger: true
  - get: 15m
    trigger: true
  - task: update-space-users
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      LDAP_PASSWORD: {{ldap_password}}
      CF_MGMT_COMMAND: update-space-users
- name: update-space-quotas
  plan:
  - get: test-cfmgmt
    passed: [create-spaces]
    trigger: true
  - task: update-space-quotas
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: update-space-quotas
- name: update-space-security-groups
  plan:
  - get: test-cfmgmt
    passed: [create-spaces]
    trigger: true
  - task: update-space-security-groups
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: update-space-security-groups
- name: update-org-users
  plan:
  - get: test-cfmgmt
    passed: [create-orgs]
    trigger: true
  - get: 15m
    trigger: true
  - task: update-org-users
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      LDAP_PASSWORD: {{ldap_password}}
      CF_MGMT_COMMAND: update-org-users
- name: update-org-quotas
  plan:
  - get: test-cfmgmt
    passed: [create-orgs]
    trigger: true
  - task: update-org-quotas
    file: test-cfmgmt/ci/tasks/cf-mgmt.yml
    params:
      SYSTEM_DOMAIN: {{system_domain}}
      USER_ID: {{user_id}}
      PASSWORD: {{password}}
      CONFIG_DIR: ./config
      CLIENT_SECRET: {{client_secret}}
      CF_MGMT_COMMAND: update-org-quotas
